name: wallet_online
version: 1.0.0+1
publish_to: none
description: Wallet Online.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  http: ^0.13.4
  animated_splash_screen: ^1.1.0
  flutter_spinkit: ^5.0.0
  cached_network_image: 3.1.0+1
  auto_size_text: 3.0.0
  shared_preferences: 2.0.9
  sqflite: 2.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
  uses-material-design: true

flutter_icons: 
  android: app_icon_round
  image_path: assets/icons/app_icon_round.png
  ios: true

