name: wallet_manager
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The Package
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  sqflite: ^1.3.2+3
  intl: ^0.17.0
  flutter_spinkit: ^5.0.0
  animated_splash_screen: ^1.1.0
  toast: ^0.1.5
  cached_network_image: ^2.5.1
  fl_chart: ^0.35.0


dev_dependencies:
  #change_app_package_name: ^1.0.0
  #flutter_launcher_icons: ^0.9.0
  #flutter_launcher_name: "^0.0.1"

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "iManager"

flutter_icons:
  android: "app_icon_round"
  ios: true
  image_path: "assets/icons/app_icon_round.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icons/